server:
  port: 8080

management:
  server:
    port: 18080
  endpoints:
    web:
      exposure:
        include: '*'
        #exclude: info,env,beans
spring:
  application:
    name: com.lind.basic
  profiles:
    active: dev
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://172.17.0.22:30607/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: Bdyh@2019
  elasticsearch:
    jest:
      uris: http://127.0.0.1:9200

mybatis-plus:
  # 放在resource目录 classpath:/mapper/*.xml
  mapper-locations: classpath:/mapper/*.xml,classpath:/mapper/**/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.lind.basic.entity.**
  typeEnumsPackage: com.lind.basic.entity.**
  global-config:
    # 主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    # 字段策略 0:"忽略判断",1:"非 NULL 判断",2:"非空判断"
    field-strategy: 2
    # 驼峰下划线转换
    db-column-underline: true
    # 刷新mapper 调试神器
    refresh-mapper: true
    # 数据库大写下划线转换
    #capital-mode: true
    # 逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false


author: zhangzhanling
passport:
  type: md5
  users:
    admin
    user
  authrates: read,write #不能用双引号
  default:
    username: zzl
    passworld: 123

config-attributes:
  value: 345                          #对应单个值
  valueArray: 1,2,3,4,5,6,7,8,9      #对应数组
  valueList:                         #对应list
    -13579
    -246810
  valueMap:                          #对应map
    name: lili
    age: 20
    sex: female
  valueMapList:                      #对应list<map>
    - name: bob
      age: 21
    - name: caven
      age: 31

